language: go
go:
  - 1.7
  - tip

before_install:
  - go get github.com/jessevdk/go-flags
  - go get github.com/opesun/goquery

  script:
  - test -z "$(gofmt -s -l . | tee /dev/stderr)"
  - go test -v ./...